<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <!-- Testing -->
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Google.Protobuf" Version="3.35.1" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageVersion Include="Grpc.Core.Api" Version="2.80.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.82.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
  <!-- Additional versions are appended below by 'dotnet add package'. -->
</Project>